# Generated by Django 3.1.4 on 2021-01-26 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210126_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='car_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='api.car'),
        ),
    ]
